from crypto_engine.argon2.addressing import (
    map_j1_to_index,
    reference_area_size,
    select_reference_lane,
    compute_reference_position,
    select_reference_block,
)


def test_basic_mapping():

    reference_size = 32

    test_values = [
        0,
        1,
        2,
        0x10000000,
        0x80000000,
        0xFFFFFFFF
    ]

    for j1 in test_values:

        result = map_j1_to_index(
            j1,
            reference_size
        )

        print(
            f"J1 = {j1:08x} "
            f"-> index = {result}"
        )

        assert (
            0 <= result < reference_size
        )

    print()
    print("Basic J1 mapping test passed.")

def test_reference_selection():

    j1 = 0xebd17f1d
    j2 = 0x61250f62

    lane_count = 4
    current_lane = 0

    reference_lane = select_reference_lane(
        j2,
        current_lane,
        lane_count,
    )

    position = compute_reference_position(
        j1,
        23,
    )

    print()
    print(f"J1 = {j1:08x}")
    print(f"J2 = {j2:08x}")
    print(f"Reference lane = {reference_lane}")
    print(f"Relative reference position = {position}")

    assert 0 <= reference_lane < lane_count
    assert 0 <= position < 23

    print("Reference lane selection: PASS")
    print("Reference position calculation: PASS")


def test_reference_area_size():

    lane_length = 32
    segment_length = lane_length // 4

    tests = [
        (0, 0, 2),
        (0, 1, 0),
        (0, 2, 0),
        (0, 3, 0),
        (1, 0, 7),
    ]

    for pass_number, slice_number, position in tests:

        size = reference_area_size(
            pass_number,
            slice_number,
            position,
            lane_length,
            segment_length
        )

        print(
            f"pass={pass_number}, "
            f"slice={slice_number}, "
            f"position={position} "
            f"-> reference area={size}"
        )

        assert size > 0
        assert size <= lane_length

    print()
    print("Reference-area tests passed.")

def test_reference_block_selection():

    # Values generated by our address-generation test.
    j1 = 0xEBD17F1D
    j2 = 0x61250F62

    lane_count = 4
    lane_length = 32

    reference_lane, reference_index = (
        select_reference_block(
            j1=j1,
            j2=j2,
            pass_number=0,
            slice_number=2,
            position=0,
            current_lane=0,
            lane_count=lane_count,
            lane_length=lane_length,
        )
    )

    print()
    print(
        f"Reference lane = {reference_lane}"
    )

    print(
        f"Reference index = {reference_index}"
    )

    assert 0 <= reference_lane < lane_count
    assert 0 <= reference_index < lane_length

    print(
        "Reference block selection: PASS"
    )


def main():

    test_basic_mapping()
    test_reference_area_size()
    test_reference_selection()
    test_reference_block_selection()

    print()
    print("All addressing tests passed.")


if __name__ == "__main__":
    main()  